# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Unrelease Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        default: "0.0.0"
        type: string

jobs:
  unpublish_ts_library:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HDML_FOUNDATION_DOCKER_NAME }}
          password: ${{ secrets.HDML_FOUNDATION_DOCKER }}
      - name: Replace devcontainer.json to CI version
        run: |
          rm .devcontainer/devcontainer.json
          mv .devcontainer/devcontainer_ci.json .devcontainer/devcontainer.json
      - name: Setup NPM Registry
        run: echo //registry.npmjs.org/:_authToken=$HDML_FOUNDATION_NPM > lib/ts/.npmrc
        env:
          HDML_FOUNDATION_NPM: ${{ secrets.HDML_FOUNDATION_NPM }}
      - name: Unpublish TS library
        uses: devcontainers/ci@v0.3
        with:
          push: never
          cacheFrom: hdio/hdml-schemas-dev
          runCmd: |
            cd lib/ts
            npm unpublish @hdml/schemas@${{ inputs.version }}